name: huni_sa_tribu
description: A digital museum platform for indigenous music and culture
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^7.0.1
  flutter_tts: ^4.0.2      # ðŸ‘ˆ NEW: Text-to-speech
  audioplayers: ^6.0.0    # ðŸ‘ˆ NEW: Audio playback
  http: ^1.5.0            # ðŸ‘ˆ NEW: HTTP requests 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ðŸ‘ˆ NEW: Enable assets
  assets:
    - assets/images/
    - assets/audio/
    - assets/videos/
    - assets/artifacts/
    - assets/image/background/logging/
    - assets/fonts/
    

    # Add your fonts here if using custom fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf # Make sure this font file exists
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Abril Fatface
      fonts:
        - asset: fonts/AbrilFatface-Regular.ttf