name: huni_sa_tribu
description: A digital museum platform for indigenous music and culture
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^7.0.1
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0
  http: ^1.5.0
  provider: ^6.0.5
  video_player: ^2.10.0
  shared_preferences: ^2.1.1
  #video_thumbnail: ^0.5.0
  #path_provider: ^2.0.14
  rename_app: ^1.6.5
  # For detecting widget visibility in the viewport during scrolling, useful for lazy loading videos.
  visibility_detector: ^0.4.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: false
  remove_alpha_ios: true
  image_path: "assets/images/application_icon.png" 

flutter_native_splash:
  color: "#1B4332"
  image: assets/images/app_icon.png 
  android: true
  ios: false 

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/english/
    - assets/audio/cebuano/
    - assets/audio/kagan/
    - assets/audio/mansaka/
    - assets/audio/mandaya/